version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
      reviewers:
          - 'AllenInstitute/app-dev'
      commit-message:
          prefix: 'chore(deps):'
