/**
 * @module shaders
 *
 * WGSL authoring + codegen: types, attributes, declarations, whole-shader assembly, and the
 * vertex-format / vertex-input-interface helpers.
 */
export type {
    AlignAttribute,
    BlendSrcAttribute,
    BuiltinAttribute,
    ComputeAttribute,
    ConstAttribute,
    DiagnosticAttribute,
    FragmentAttribute,
    FunctionAttribute,
    IdAttribute,
    InterpolateAttribute,
    InvariantAttribute,
    LocationAttribute,
    MustUseAttribute,
    SizeAttribute,
    VariableOrValueAttribute,
    VertexAttribute,
    WorkgroupSizeAttribute,
} from './attributes';
export {
    align,
    blendSrc,
    builtin,
    compute,
    constAttr,
    attrs,
    diagnostic,
    fragment,
    id,
    interpolate,
    invariant,
    location,
    mustUse,
    size,
    vertex,
    workgroupSize,
} from './attributes';
export type {
    AliasDeclaration,
    ConstValueDeclaration,
    Declaration,
    DeclarationGenerator,
    FunctionDeclaration,
    FunctionParameterDeclaration,
    FunctionReturnTypeDeclaration,
    IdentifierDeclaration,
    OverrideValueDeclaration,
    PrivateVariableDeclaration,
    ResourceDeclaration,
    ResourceIdentifierDeclaration,
    SamplerVariableDeclaration,
    StorageVariableDeclaration,
    StructDecl,
    StructDeclaration,
    StructMemberDeclaration,
    TextureVariableDeclaration,
    TypeIdentifier,
    UniformVariableDeclaration,
    ValueDeclaration,
    WgslType,
    WorkgroupVariableDeclaration,
} from './declarations';
export {
    alias,
    computeEntry,
    constant,
    decls,
    fragmentEntry,
    func,
    member,
    override,
    param,
    privateVar,
    returns,
    sampler,
    storage,
    struct,
    texture,
    uniform,
    vertexEntry,
    workgroupVar,
} from './declarations';
export type { WgslShader } from './shader';
export { asSource, isWgslShader, shader } from './shader';
// ---- Vertex formats + vertex input interface -------------------------------------------------
export * from './vertex-format';
export * from './vertex-interface';
export type {
    WgslAtomic,
    WgslDataType,
    WgslDepthMultisampledTexture,
    WgslDepthTexture,
    WgslDepthTextureDimension,
    WgslExternalTexture,
    WgslFixedArray,
    WgslFloatScalarType,
    WgslMat,
    WgslMultisampledTexture,
    WgslNumericScalarType,
    WgslRuntimeArray,
    WgslSampledType,
    WgslSampler,
    WgslSamplerComparison,
    WgslScalar,
    WgslScalarType,
    WgslStorageAccessMode,
    WgslStorageTexture,
    WgslStorageTextureDimension,
    WgslTexelFormat,
    WgslTexture,
    WgslTextureDataType,
    WgslTextureDimension,
    WgslVec,
} from './wgsl-types';
export {
    types,
    atomic,
    bool,
    depthTexture,
    f16,
    f32,
    fixedArray,
    i32,
    mat,
    mat2x2f,
    mat2x2h,
    mat2x3f,
    mat2x3h,
    mat2x4f,
    mat2x4h,
    mat3x2f,
    mat3x2h,
    mat3x3f,
    mat3x3h,
    mat3x4f,
    mat3x4h,
    mat4x2f,
    mat4x2h,
    mat4x3f,
    mat4x3h,
    mat4x4f,
    mat4x4h,
    multisampledTexture,
    runtimeArray,
    sampler_comparison,
    scalar,
    storageTexture,
    texture_depth_multisampled_2d,
    texture_external,
    u32,
    vec,
    vec2f,
    vec2h,
    vec2i,
    vec2u,
    vec3f,
    vec3h,
    vec3i,
    vec3u,
    vec4f,
    vec4h,
    vec4i,
    vec4u,
    wgslTypeName,
} from './wgsl-types';
