name: CI

on: [pull_request]

concurrency:
    # Cancels workflows that are already running when a new one is triggered for a branch
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup pnpm
              uses: pnpm/setup@v1
              with:
                  cache: true

            - name: Build
              run: pnpm build

    format:
        name: Format
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup pnpm
              uses: pnpm/setup@v1
              with:
                  cache: true

            - name: Format
              run: pnpm fmt:check

    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup pnpm
              uses: pnpm/setup@v1
              with:
                  cache: true

            - name: Lint
              run: pnpm lint:check

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup pnpm
              uses: pnpm/setup@v1
              with:
                  cache: true

            - name: Build libraries
              run: pnpm build

            - name: Test
              run: pnpm test

    typecheck:
        name: Typecheck
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup pnpm
              uses: pnpm/setup@v1
              with:
                  cache: true

            - name: Build
              run: pnpm build

            - name: Typecheck
              run: pnpm typecheck
